[workspace]
resolver = "2"
members = [
    "lib-garble-rs",
    "ipfs-client-http-req",
]

# lib-garble-rs is REALLY slow in debug
[profile.bench]
inherits = "release"
debug = 1

################################################################################
[patch."https://github.com/Interstellar-Network/swanky.git"]
fancy-garbling = { path = "../swanky/fancy-garbling/" }

# [patch."https://github.com/Interstellar-Network/pallets.git"]
# ocw-common = { path = "../pallets/ocw-common/" }
################################################################################