name: Build and Test Android App

on:
  push:

jobs:
  # TODO split test and lint; but that REQUIRE caching else recompile from scratch in between
  rust:
    runs-on: ubuntu-latest
    steps:
      # install build dependencies
      # MUST match the same step in Dockerfile
      # - name: Install dependencies
      #   run: sudo apt-get update && sudo apt-get install -y libboost-dev

      - uses: Interstellar-Network/gh-actions/prepare@v2
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: false

      - uses: Interstellar-Network/gh-actions/prepare_rust@v2
        with:
          toolchain_toolchain: stable
      # for now https://github.com/actions-rs/toolchain only support one "target"...
      # TODO? "x86_64-unknown-linux-gnu"
      - run: rustup target add armv7-linux-androideabi aarch64-linux-android

      ##########################################################################
      # NOTE "protoc-VERSION-HOST.zip"(contains protoc itself)
      # and "protobuf-cpp-VERSION.tar.gz" contains the source code for eg "src/google/protobuf/port_def.inc"
      # What we download in CI, and what shared/rust/circuit_evaluate/build.rs expects SHOULD MATCH!
      # DO NOT change the structure, else build.rs will fail!
      #
      # Needed for at least libp2p
      - name: Install protoc custom prebuilt binary
        run: |
          mkdir /home/runner/protoc
          cd /home/runner/protoc
          wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip -O prebuilt.zip
          unzip prebuilt.zip
          rm prebuilt.zip
          echo "PROTOC=/home/runner/protoc/bin/protoc" >> $GITHUB_ENV
        shell: bash

      ##########################################################################
      # cf https://github.com/android-actions/setup-android

      # TODO apparently this is not cached?
      # if not: cache the whole "Setup Android SDK"+"Delete old NDK v23"+"Install NDK v24"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # else: "Warning: Observed package id 'ndk;23.2.8568313' in inconsistent location '/usr/local/lib/android/sdk/ndk-bundle' (Expected '/usr/local/lib/android/sdk/ndk/23.2.8568313')"
      - name: Delete old NDK v23
        # version required else: "Warning: Failed to find package 'ndk'"
        run: sdkmanager --uninstall "ndk;23.2.8568313"
      - name: Install NDK v25
        # version required else: "Warning: Failed to find package 'ndk'"
        run: sdkmanager "ndk;25.1.8937393"

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/rust-build-and-test@v2
        with:
          # For now we the benches just output to stdout and we do nothing with it
          # TODO performance regression testing
          check_args: --profile=bench
          test_args: --profile=bench

      # TODO move into separate action? ideally into a JS action "post" that setup ccache?
      # NOTE: remove if using "rust-build-and-test"
      - name: Print ccache/sccache stats
        # display stats even if tests failed
        if: always()
        run: |
          ccache --show-stats || true
          sccache --show-stats || true
        shell: bash
